image: "rust:latest"

cache:
  paths:
    - target/
    - .cargo

before-script:
  - export CARGO_HOME=.cargo
    
stages:
  - build
  - test
  - deploy

cargo:build:
  stage: build
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo build


cargo:test:
  stage: test
  script:
  - cargo test --all
  
pages:
  stage: deploy
  script:
  - cargo doc
  - mkdir .public
  - cp -r target/doc .public/doc
  - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
