image: "rust:latest"

cache:
  paths:
    - target/
    - .cargo

before_script:
  - export CARGO_HOME=.cargo
    
stages:
  - build
  - test
  - doc
  - deploy

cargo:build:
  stage: build
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo build


cargo:test:
  stage: test
  script:
  - cargo test --all

cargo:doc:
  stage: doc
  script:
  - cargo doc
  - mkdir -p public/doc
  - cp -r target/doc public/doc
  artifacts:
    paths:
      - public/doc
      
cargo:mdbook:
  stage: doc
  script:
  - mkdir -p public/book
  - cargo install mdbook
  - .cargo/bin/mdbook build book -d public/book
  artifacts:
    paths:
      - public/book
  
pages:
  stage: deploy
  script:
  - ls -R public | wc
  artifacts:
    paths:
      - public
  only:
    - master
  dependencies:
    - cargo:doc
    - cargo:mdbook
