image: "rust:latest"

cache:
  paths:
    - target/
    - public/
    - .cargo
    - .public

before_script:
  - export CARGO_HOME=.cargo
    
stages:
  - build
  - test
  - doc
  - deploy

cargo:build:
  stage: build
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo build


cargo:test:
  stage: test
  script:
  - cargo test --all

cargo:doc:
  stage: doc
  script:
  - cargo doc
  - mkdir .public
  - cp -r target/doc .public/doc

cargo:mdbook:
  stage: doc
  script:
  - mkdir .public
  - cargo install mdbook
  - .cargo/bin/mdbook build book -d .public/book 
  
pages:
  stage: deploy
  script:
  - cp -r .public public
  artifacts:
    paths:
      - public
  only:
    - master
