[package]
name = "katjing"
version = "0.1.0"
authors = ["johlrogge <joakim.x230@agical.se>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
thiserror = "1.0"

[dev-dependencies]
doc-comment = "0.3"
