[package]
name = "katjing"
version = "0.1.0"
authors = ["Joakim Ohlrogge <joakim.ohlrogge@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
paste = "0.1"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"